/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomSheet: typeof import('./src/components/BottomSheet.vue')['default']
    CartLine: typeof import('./src/components/CartLine.vue')['default']
    CartPanel: typeof import('./src/components/CartPanel.vue')['default']
    CategoryRail: typeof import('./src/components/CategoryRail.vue')['default']
    CustomerSheet: typeof import('./src/components/CustomerSheet.vue')['default']
    HeldSheet: typeof import('./src/components/HeldSheet.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    ItemGrid: typeof import('./src/components/ItemGrid.vue')['default']
    MobileCartBar: typeof import('./src/components/MobileCartBar.vue')['default']
    PaySheet: typeof import('./src/components/PaySheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanSheet: typeof import('./src/components/ScanSheet.vue')['default']
    ShiftSheet: typeof import('./src/components/ShiftSheet.vue')['default']
    StockActionSheet: typeof import('./src/components/StockActionSheet.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
