/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppRail: typeof import('./src/components/AppRail.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    BarList: typeof import('./src/components/charts/BarList.vue')['default']
    BottomSheet: typeof import('./src/components/BottomSheet.vue')['default']
    CartLine: typeof import('./src/components/CartLine.vue')['default']
    CartPanel: typeof import('./src/components/CartPanel.vue')['default']
    ChartCard: typeof import('./src/components/charts/ChartCard.vue')['default']
    CustomerSheet: typeof import('./src/components/CustomerSheet.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DocumentFormSheet: typeof import('./src/components/DocumentFormSheet.vue')['default']
    DocumentModal: typeof import('./src/components/DocumentModal.vue')['default']
    HeldSheet: typeof import('./src/components/HeldSheet.vue')['default']
    ItemCell: typeof import('./src/components/ItemCell.vue')['default']
    ItemGrid: typeof import('./src/components/ItemGrid.vue')['default']
    MasterSheet: typeof import('./src/components/MasterSheet.vue')['default']
    MobileCartBar: typeof import('./src/components/MobileCartBar.vue')['default']
    ModuleTabs: typeof import('./src/components/ModuleTabs.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PaySheet: typeof import('./src/components/PaySheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanSheet: typeof import('./src/components/ScanSheet.vue')['default']
    ShareBar: typeof import('./src/components/charts/ShareBar.vue')['default']
    ShiftSheet: typeof import('./src/components/ShiftSheet.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    StatTiles: typeof import('./src/components/StatTiles.vue')['default']
    StockActionSheet: typeof import('./src/components/StockActionSheet.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    TrendChart: typeof import('./src/components/charts/TrendChart.vue')['default']
  }
}
